### ISSUE TITLE
Video from mobile crashes videocompositor

### ISSUE THREAD

**Issue by pkrucz00** [membraneframework-labs/membrane_live#110]
How to recreate:

1. User from desktop joins as a presenter.
2. User from mobile joins as a presenter.
3. HLS crashes with the given error:

```
[error] [:compositor] Error handling action {:split, {:handle_process, [[:master, %Membrane.Buffer{payload: <<16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, ...>>, pts: 54416666666, dts: nil, metadata: %{}}]]}} returned by callback Membrane.VideoMixer.MasterMixer.handle_process_list

[error] GenServer #PID<0.1503.0> terminating
** (MatchError) no match of right hand side value: {:error, :error_initializing_filters}
    (membrane_video_mixer_plugin 0.1.0) lib/membrane/video_mixer/master_mixer.ex:252: Membrane.VideoMixer.MasterMixer.mix/1
    (membrane_video_mixer_plugin 0.1.0) lib/membrane/video_mixer/master_mixer.ex:225: Membrane.VideoMixer.MasterMixer.mix_n/3
    (membrane_video_mixer_plugin 0.1.0) lib/membrane/video_mixer/master_mixer.ex:213: Membrane.VideoMixer.MasterMixer.mix_if_ready/1
    (membrane_core 0.10.2) lib/membrane/core/callback_handler.ex:140: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.10.2) lib/membrane/core/callback_handler.ex:118: anonymous fn/6 in Membrane.Core.CallbackHandler.exec_and_handle_split_callback/6
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (membrane_core 0.10.2) lib/membrane/core/callback_handler.ex:182: anonymous fn/5 in Membrane.Core.CallbackHandler.handle_callback_result/5
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (membrane_core 0.10.2) lib/membrane/core/element/demand_handler.ex:92: Membrane.Core.Element.DemandHandler.do_supply_demand/2
    (membrane_core 0.10.2) lib/membrane/core/element/demand_handler.ex:73: Membrane.Core.Element.DemandHandler.supply_demand/2
    (membrane_core 0.10.2) lib/membrane/core/element.ex:177: Membrane.Core.Element.handle_info/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {Membrane.Core.Message, :buffer, [%Membrane.Buffer{payload: <<16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, ...>>, pts: 54416666666, dts: nil, metadata: %{}}], [for_pad: :master]}
[error] Endpoint "29dfe4d3-f83f-4e0e-8db7-aeeabceedc3a" has crashed!
[error] Endpoint crashed handling error: This peer doesn't exist already!
``` 

It's possibly due to the inability of the new compositor to handle video with too small resolution.

**Comment by LVala** [comment]
Solved by moving to `membrane_video_compositor_plugin`.
